"""
DyME-aligned OPD on ChartQA with teacher-correct gating.

Routing:
- all-wrong group -> SFT for every completion
- correct completion -> GRPO
- wrong completion -> 7B teacher answer probe
- teacher-correct wrong completion -> SRKL OPD + optional teacher-trajectory FKL
- teacher-wrong wrong completion -> SFT

Teacher context is no-gold by default: format instructions + visual facts.
"""
import os

import config.config_opd_7b_chartqa as base
from config.env_overrides import (
    env_bool,
    env_float,
    env_int,
    env_list,
    env_optional_float,
    env_optional_int,
    env_str,
)
from config.config import DEPLOT_CONFIG as _BASE_DEPLOT_CONFIG
from config.visual_supervision_defaults import build_visual_supervision_config
from data_utils.paths import OUTPUTS_DIR
from opsd_utils.privileged.providers import CHARTQA_ORACLE_HINT

# --- Training defaults (single source of truth) ---
OPSD_MODE = "dyme_teacher_probe_opd"
PRIVILEGE_PROFILE = "hybrid"
PROBE_PROVIDERS = ["format_only", "visual_facts_deplot"]
OUTPUT_DIR = os.path.join(OUTPUTS_DIR, "opd-7b-dyme-probe-chartqa")
CHARTQA_SHORT_ANSWER_HINT = (
    "Answer the chart question using only the chart image and provided visual evidence. "
    "Keep reasoning concise. Finish with exactly one final line:\n"
    "Answer: <short answer>"
)

TEACHER_PROBE_ENABLED = True
TEACHER_TRAJECTORY_ENABLED = True
TEACHER_PROBE_PROMPT_PROFILE = "chartqa_short_answer"
LOSS_TYPE = "srkl"
SRKL_ALPHA = 0.1
OPSD_WEIGHT = 1.0
GRPO_WEIGHT = 1.0
TEACHER_TRAJ_FKL_WEIGHT = 0.5
TEACHER_TRAJ_WEIGHT_DECAY = False
TEACHER_TRAJ_DECAY_START_STEP = 294
TEACHER_TRAJ_DECAY_END_STEP = 441
TEACHER_TRAJ_DECAY_START_PROGRESS = 0.25
TEACHER_TRAJ_DECAY_END_PROGRESS = 0.50
TEACHER_TRAJ_FINAL_WEIGHT = 0.0
OPSD_VARIANCE_ADAPTIVE = False
OPSD_ADAPTIVE_STD_TARGET = 0.25
OPSD_ADAPTIVE_MAX_MULT = 2.0
OPSD_WEIGHT_DECAY = False
OPSD_DECAY_START_STEP = 294
OPSD_DECAY_END_STEP = 441
OPSD_DECAY_START_PROGRESS = 0.50
OPSD_DECAY_END_PROGRESS = 0.75
OPSD_FINAL_WEIGHT = 0.5
OPSD_MAX_PER_PROMPT_AFTER_STEP = 0
OPSD_MAX_PER_PROMPT = 0
OPSD_ROUTE_CAP_START_PROGRESS = 0.50
OPSD_OVERFLOW_ROUTE = "sft"
EFFECTIVE_SAMPLING_ENABLED = False
EFFECTIVE_SAMPLING_AFTER_STEP = 294
EFFECTIVE_SAMPLING_START_PROGRESS = 0.50
EFFECTIVE_SAMPLING_MIXED_WEIGHT = 4.0
EFFECTIVE_SAMPLING_ALL_WRONG_WEIGHT = 1.0
EFFECTIVE_SAMPLING_ALL_CORRECT_WEIGHT = 0.7
EFFECTIVE_SAMPLING_UNKNOWN_WEIGHT = 1.0
EFFECTIVE_SAMPLING_REWARD_STD_BONUS = 2.0
POSITIVE_REPLAY_ENABLED = False
POSITIVE_REPLAY_DATASET = ""
POSITIVE_REPLAY_WEIGHT = 0.1
POSITIVE_REPLAY_BATCH_SIZE = 1
POSITIVE_REPLAY_AFTER_STEP = 0
POSITIVE_REPLAY_UNTIL_STEP = 0
POSITIVE_REPLAY_MAX_ROWS = 0
POSITIVE_REPLAY_SEED = 13
ROLLOUT_REPLAY_ENABLED = False
ROLLOUT_REPLAY_WEIGHT = 0.05
ROLLOUT_REPLAY_CAPACITY = 256
ROLLOUT_REPLAY_BATCH_SIZE = 2
ROLLOUT_REPLAY_AFTER_STEP = 50
ROLLOUT_REPLAY_UNTIL_STEP = 0
ROLLOUT_REPLAY_MAX_AGE_STEPS = 64
ROLLOUT_REPLAY_MIN_ABS_ADVANTAGE = 0.05
ROLLOUT_REPLAY_CORRECT_THRESHOLD = 0.5
ROLLOUT_REPLAY_PRIORITY_ALPHA = 1.0
ROLLOUT_REPLAY_POSITIVE_ONLY = True
ROLLOUT_REPLAY_SEED = 17
EFFECTIVE_GROUP_FILTER_ENABLED = False
EFFECTIVE_GROUP_FILTER_AFTER_STEP = 294
EFFECTIVE_GROUP_FILTER_ALL_WRONG_KEEP = 1
EFFECTIVE_GROUP_FILTER_ALL_CORRECT = True
SIGNAL_AWARE_ROUTING = False
SIGNAL_REWARD_STD_MIN = 0.05
DEGENERATE_HARD_OVERRIDE = False
CLIPPED_HARD_OVERRIDE = False
PERCEPTION_REWARD_ENABLED = False
PERCEPTION_REWARD_SOURCE = "image_teacher"
PERCEPTION_REWARD_WEIGHT = 0.2
PERCEPTION_REWARD_BATCH_SIZE = 4
PERCEPTION_REWARD_MAX_NEW_TOKENS = 8
EVAL_FORMAT_REWARD_ENABLED = False
EVAL_FORMAT_REWARD_WEIGHT = 0.1
TEACHER_CORRECT_REPAIR_MODE = "opd"
TEACHER_SFT_REPAIR_SCOPE = "all_wrong"
TEACHER_SFT_REPAIR_SLOTS = 1
TEACHER_SFT_TARGET_MAX_TOKENS = 256
TEACHER_SFT_SANITIZE_PRIVILEGED = True
TEACHER_SFT_TARGET_CONSTRAINT = "chartqa_hint"
TEACHER_SFT_TARGET_STYLE = "chartqa_hint"
ONLINE_SFT_TARGET_STYLE = ""
SFT_COLD_START_STEPS = 0
PHASE_SCHEDULE_MODE = "step"
DYNAMIC_TRIGGER_MONITOR_ENABLED = True
DYNAMIC_TRIGGER_EMA_ALPHA = 0.10
DYNAMIC_TRIGGER_MIN_PROGRESS = 0.20
DYNAMIC_TRIGGER_PATIENCE = 20
DYNAMIC_TRIGGER_SAMPLING_MIXED_MAX = 0.20
DYNAMIC_TRIGGER_SAMPLING_ZERO_MIN = 0.70
DYNAMIC_TRIGGER_RL_MIXED_MIN = 0.30
DYNAMIC_TRIGGER_RL_ZERO_MAX = 0.30
ADAPTIVE_SUPERVISION_ENABLED = False
ADAPTIVE_READINESS_SOURCE = "mixed_zero"
ADAPTIVE_EMA_ALPHA = 0.10
ADAPTIVE_TARGET_READINESS = 0.20
ADAPTIVE_OPSD_INITIAL_WEIGHT = 1.50
ADAPTIVE_OPSD_FINAL_WEIGHT = 0.50
ADAPTIVE_TEACHER_INITIAL_WEIGHT = 0.50
ADAPTIVE_TEACHER_FINAL_WEIGHT = 0.0
ADAPTIVE_OPSD_INITIAL_CAP = 8
ADAPTIVE_OPSD_FINAL_CAP = 2
GLOBAL_SIGNAL_LOGGING_ENABLED = False
SIGNAL_UTILITY_ROUTING_ENABLED = False
SIGNAL_UTILITY_REWARD_STD_SCALE = 0.10
SIGNAL_UTILITY_ALLOW_GRPO_ON_FORMAT_BAD = False
SIGNAL_UTILITY_GRPO_BASE = 0.05
SIGNAL_UTILITY_GRPO_CORRECT_BONUS = 1.00
SIGNAL_UTILITY_GRPO_MIXED_BONUS = 0.25
SIGNAL_UTILITY_GRPO_SIGNAL_WEIGHT = 0.40
SIGNAL_UTILITY_GRPO_READINESS_WEIGHT = 0.70
SIGNAL_UTILITY_OPD_BASE = 0.10
SIGNAL_UTILITY_OPD_TEACHER_BONUS = 0.45
SIGNAL_UTILITY_OPD_WRONG_BONUS = 0.20
SIGNAL_UTILITY_OPD_GAP_WEIGHT = 0.55
SIGNAL_UTILITY_OPD_ALL_WRONG_BONUS = 0.20
SIGNAL_UTILITY_OPD_TEACHER_NEED_WEIGHT = 0.60
SIGNAL_UTILITY_OPD_FORMAT_PENALTY = 1.00
SIGNAL_UTILITY_SFT_BASE = 0.02
SIGNAL_UTILITY_SFT_FORMAT_BAD_BONUS = 1.10
SIGNAL_UTILITY_SFT_CLIPPED_BONUS = 0.80
SIGNAL_UTILITY_SFT_ALL_WRONG_BONUS = 0.20
SIGNAL_UTILITY_SFT_LOW_SIGNAL_BONUS = 0.25
SIGNAL_UTILITY_SFT_CORRECT_PENALTY = 1.00
SIGNAL_UTILITY_SKIP_CLIPPED_WITHOUT_TEACHER = False
SIGNAL_UTILITY_MODE_STABLE_ENABLED = False
SIGNAL_UTILITY_EMA_BETA = 0.80
SIGNAL_UTILITY_SWITCH_MARGIN = 0.20
SIGNAL_UTILITY_MIN_HOLD_STEPS = 2
CHART_COT_VERIFY_ENABLED = False
CHART_COT_GATE_MODE = "off"
CHART_COT_REQUIRE_Q3 = True
CHART_COT_LOG_SAMPLES = True
CHART_COT_MAX_LOG_SAMPLES = 8

# Full ChartQA run: follow num_train_epochs unless DYME_MAX_STEPS is explicitly set.
NUM_TRAIN_EPOCHS = env_int("DYME_NUM_TRAIN_EPOCHS", 10)

# Optional env overrides (ablation / server paths)
OPSD_MODE = env_str("DYME_OPSD_MODE", OPSD_MODE)
PRIVILEGE_PROFILE = env_str("DYME_OPSD_PRIVILEGE_PROFILE", PRIVILEGE_PROFILE)
PROBE_PROVIDERS = env_list("DYME_TEACHER_PROBE_PROVIDERS", env_list("DYME_OPSD_PROVIDERS", PROBE_PROVIDERS))
OUTPUT_DIR = env_str("DYME_OUTPUT_DIR", OUTPUT_DIR)

TEACHER_PROBE_ENABLED = env_bool("DYME_TEACHER_PROBE", TEACHER_PROBE_ENABLED)
TEACHER_TRAJECTORY_ENABLED = env_bool("DYME_TEACHER_TRAJECTORY", TEACHER_TRAJECTORY_ENABLED)
TEACHER_PROBE_PROMPT_PROFILE = env_str("DYME_TEACHER_PROBE_PROMPT_PROFILE", TEACHER_PROBE_PROMPT_PROFILE)
LOSS_TYPE = env_str("DYME_OPSD_LOSS_TYPE", LOSS_TYPE)
SRKL_ALPHA = env_float("DYME_OPSD_SRKL_ALPHA", SRKL_ALPHA)
OPSD_WEIGHT = env_float("DYME_OPSD_WEIGHT", OPSD_WEIGHT)
GRPO_WEIGHT = env_float("DYME_GRPO_WEIGHT", GRPO_WEIGHT)
TEACHER_TRAJ_FKL_WEIGHT = env_float("DYME_TEACHER_TRAJ_FKL_WEIGHT", TEACHER_TRAJ_FKL_WEIGHT)
TEACHER_TRAJ_WEIGHT_DECAY = env_bool("DYME_TEACHER_TRAJ_WEIGHT_DECAY", TEACHER_TRAJ_WEIGHT_DECAY)
TEACHER_TRAJ_DECAY_START_STEP = env_int("DYME_TEACHER_TRAJ_DECAY_START_STEP", TEACHER_TRAJ_DECAY_START_STEP)
TEACHER_TRAJ_DECAY_END_STEP = env_int("DYME_TEACHER_TRAJ_DECAY_END_STEP", TEACHER_TRAJ_DECAY_END_STEP)
TEACHER_TRAJ_DECAY_START_PROGRESS = env_float("DYME_TEACHER_TRAJ_DECAY_START_PROGRESS", TEACHER_TRAJ_DECAY_START_PROGRESS)
TEACHER_TRAJ_DECAY_END_PROGRESS = env_float("DYME_TEACHER_TRAJ_DECAY_END_PROGRESS", TEACHER_TRAJ_DECAY_END_PROGRESS)
TEACHER_TRAJ_FINAL_WEIGHT = env_float("DYME_TEACHER_TRAJ_FINAL_WEIGHT", TEACHER_TRAJ_FINAL_WEIGHT)
OPSD_VARIANCE_ADAPTIVE = env_bool("DYME_OPSD_VARIANCE_ADAPTIVE", OPSD_VARIANCE_ADAPTIVE)
OPSD_ADAPTIVE_STD_TARGET = env_float("DYME_OPSD_ADAPTIVE_STD_TARGET", OPSD_ADAPTIVE_STD_TARGET)
OPSD_ADAPTIVE_MAX_MULT = env_float("DYME_OPSD_ADAPTIVE_MAX_MULT", OPSD_ADAPTIVE_MAX_MULT)
OPSD_WEIGHT_DECAY = env_bool("DYME_OPSD_WEIGHT_DECAY", OPSD_WEIGHT_DECAY)
OPSD_DECAY_START_STEP = env_int("DYME_OPSD_DECAY_START_STEP", OPSD_DECAY_START_STEP)
OPSD_DECAY_END_STEP = env_int("DYME_OPSD_DECAY_END_STEP", OPSD_DECAY_END_STEP)
OPSD_DECAY_START_PROGRESS = env_float("DYME_OPSD_DECAY_START_PROGRESS", OPSD_DECAY_START_PROGRESS)
OPSD_DECAY_END_PROGRESS = env_float("DYME_OPSD_DECAY_END_PROGRESS", OPSD_DECAY_END_PROGRESS)
OPSD_FINAL_WEIGHT = env_float("DYME_OPSD_FINAL_WEIGHT", OPSD_FINAL_WEIGHT)
OPSD_MAX_PER_PROMPT_AFTER_STEP = env_int("DYME_OPSD_MAX_PER_PROMPT_AFTER_STEP", OPSD_MAX_PER_PROMPT_AFTER_STEP)
OPSD_MAX_PER_PROMPT = env_int("DYME_OPSD_MAX_PER_PROMPT", OPSD_MAX_PER_PROMPT)
OPSD_ROUTE_CAP_START_PROGRESS = env_float("DYME_OPSD_ROUTE_CAP_START_PROGRESS", OPSD_ROUTE_CAP_START_PROGRESS)
OPSD_OVERFLOW_ROUTE = env_str("DYME_OPSD_OVERFLOW_ROUTE", OPSD_OVERFLOW_ROUTE)
EFFECTIVE_SAMPLING_ENABLED = env_bool("DYME_EFFECTIVE_SAMPLING", EFFECTIVE_SAMPLING_ENABLED)
EFFECTIVE_SAMPLING_AFTER_STEP = env_int("DYME_EFFECTIVE_SAMPLING_AFTER_STEP", EFFECTIVE_SAMPLING_AFTER_STEP)
EFFECTIVE_SAMPLING_START_PROGRESS = env_float("DYME_EFFECTIVE_SAMPLING_START_PROGRESS", EFFECTIVE_SAMPLING_START_PROGRESS)
EFFECTIVE_SAMPLING_MIXED_WEIGHT = env_float("DYME_EFFECTIVE_SAMPLING_MIXED_WEIGHT", EFFECTIVE_SAMPLING_MIXED_WEIGHT)
EFFECTIVE_SAMPLING_ALL_WRONG_WEIGHT = env_float("DYME_EFFECTIVE_SAMPLING_ALL_WRONG_WEIGHT", EFFECTIVE_SAMPLING_ALL_WRONG_WEIGHT)
EFFECTIVE_SAMPLING_ALL_CORRECT_WEIGHT = env_float("DYME_EFFECTIVE_SAMPLING_ALL_CORRECT_WEIGHT", EFFECTIVE_SAMPLING_ALL_CORRECT_WEIGHT)
EFFECTIVE_SAMPLING_UNKNOWN_WEIGHT = env_float("DYME_EFFECTIVE_SAMPLING_UNKNOWN_WEIGHT", EFFECTIVE_SAMPLING_UNKNOWN_WEIGHT)
EFFECTIVE_SAMPLING_REWARD_STD_BONUS = env_float("DYME_EFFECTIVE_SAMPLING_REWARD_STD_BONUS", EFFECTIVE_SAMPLING_REWARD_STD_BONUS)
POSITIVE_REPLAY_ENABLED = env_bool("DYME_POSITIVE_REPLAY", POSITIVE_REPLAY_ENABLED)
POSITIVE_REPLAY_DATASET = env_str("DYME_POSITIVE_REPLAY_DATASET", POSITIVE_REPLAY_DATASET)
POSITIVE_REPLAY_WEIGHT = env_float("DYME_POSITIVE_REPLAY_WEIGHT", POSITIVE_REPLAY_WEIGHT)
POSITIVE_REPLAY_BATCH_SIZE = env_int("DYME_POSITIVE_REPLAY_BATCH_SIZE", POSITIVE_REPLAY_BATCH_SIZE)
POSITIVE_REPLAY_AFTER_STEP = env_int("DYME_POSITIVE_REPLAY_AFTER_STEP", POSITIVE_REPLAY_AFTER_STEP)
POSITIVE_REPLAY_UNTIL_STEP = env_int("DYME_POSITIVE_REPLAY_UNTIL_STEP", POSITIVE_REPLAY_UNTIL_STEP)
POSITIVE_REPLAY_MAX_ROWS = env_int("DYME_POSITIVE_REPLAY_MAX_ROWS", POSITIVE_REPLAY_MAX_ROWS)
POSITIVE_REPLAY_SEED = env_int("DYME_POSITIVE_REPLAY_SEED", POSITIVE_REPLAY_SEED)
ROLLOUT_REPLAY_ENABLED = env_bool("DYME_ROLLOUT_REPLAY", ROLLOUT_REPLAY_ENABLED)
ROLLOUT_REPLAY_WEIGHT = env_float("DYME_ROLLOUT_REPLAY_WEIGHT", ROLLOUT_REPLAY_WEIGHT)
ROLLOUT_REPLAY_CAPACITY = env_int("DYME_ROLLOUT_REPLAY_CAPACITY", ROLLOUT_REPLAY_CAPACITY)
ROLLOUT_REPLAY_BATCH_SIZE = env_int("DYME_ROLLOUT_REPLAY_BATCH_SIZE", ROLLOUT_REPLAY_BATCH_SIZE)
ROLLOUT_REPLAY_AFTER_STEP = env_int("DYME_ROLLOUT_REPLAY_AFTER_STEP", ROLLOUT_REPLAY_AFTER_STEP)
ROLLOUT_REPLAY_UNTIL_STEP = env_int("DYME_ROLLOUT_REPLAY_UNTIL_STEP", ROLLOUT_REPLAY_UNTIL_STEP)
ROLLOUT_REPLAY_MAX_AGE_STEPS = env_int("DYME_ROLLOUT_REPLAY_MAX_AGE_STEPS", ROLLOUT_REPLAY_MAX_AGE_STEPS)
ROLLOUT_REPLAY_MIN_ABS_ADVANTAGE = env_float("DYME_ROLLOUT_REPLAY_MIN_ABS_ADVANTAGE", ROLLOUT_REPLAY_MIN_ABS_ADVANTAGE)
ROLLOUT_REPLAY_CORRECT_THRESHOLD = env_float("DYME_ROLLOUT_REPLAY_CORRECT_THRESHOLD", ROLLOUT_REPLAY_CORRECT_THRESHOLD)
ROLLOUT_REPLAY_PRIORITY_ALPHA = env_float("DYME_ROLLOUT_REPLAY_PRIORITY_ALPHA", ROLLOUT_REPLAY_PRIORITY_ALPHA)
ROLLOUT_REPLAY_POSITIVE_ONLY = env_bool("DYME_ROLLOUT_REPLAY_POSITIVE_ONLY", ROLLOUT_REPLAY_POSITIVE_ONLY)
ROLLOUT_REPLAY_SEED = env_int("DYME_ROLLOUT_REPLAY_SEED", ROLLOUT_REPLAY_SEED)
EFFECTIVE_GROUP_FILTER_ENABLED = env_bool("DYME_EFFECTIVE_GROUP_FILTER", EFFECTIVE_GROUP_FILTER_ENABLED)
EFFECTIVE_GROUP_FILTER_AFTER_STEP = env_int("DYME_EFFECTIVE_GROUP_FILTER_AFTER_STEP", EFFECTIVE_GROUP_FILTER_AFTER_STEP)
EFFECTIVE_GROUP_FILTER_ALL_WRONG_KEEP = env_int("DYME_EFFECTIVE_GROUP_FILTER_ALL_WRONG_KEEP", EFFECTIVE_GROUP_FILTER_ALL_WRONG_KEEP)
EFFECTIVE_GROUP_FILTER_ALL_CORRECT = env_bool("DYME_EFFECTIVE_GROUP_FILTER_ALL_CORRECT", EFFECTIVE_GROUP_FILTER_ALL_CORRECT)
SIGNAL_AWARE_ROUTING = env_bool("DYME_SIGNAL_AWARE_ROUTING", SIGNAL_AWARE_ROUTING)
SIGNAL_REWARD_STD_MIN = env_float("DYME_SIGNAL_REWARD_STD_MIN", SIGNAL_REWARD_STD_MIN)
DEGENERATE_HARD_OVERRIDE = env_bool("DYME_DEGENERATE_HARD_OVERRIDE", DEGENERATE_HARD_OVERRIDE)
CLIPPED_HARD_OVERRIDE = env_bool("DYME_CLIPPED_HARD_OVERRIDE", CLIPPED_HARD_OVERRIDE)
PERCEPTION_REWARD_ENABLED = env_bool("DYME_PERCEPTION_REWARD", PERCEPTION_REWARD_ENABLED)
PERCEPTION_REWARD_SOURCE = env_str("DYME_PERCEPTION_REWARD_SOURCE", PERCEPTION_REWARD_SOURCE)
PERCEPTION_REWARD_WEIGHT = env_float("DYME_PERCEPTION_REWARD_WEIGHT", PERCEPTION_REWARD_WEIGHT)
PERCEPTION_REWARD_BATCH_SIZE = env_int("DYME_PERCEPTION_REWARD_BATCH_SIZE", PERCEPTION_REWARD_BATCH_SIZE)
PERCEPTION_REWARD_MAX_NEW_TOKENS = env_int("DYME_PERCEPTION_REWARD_MAX_NEW_TOKENS", PERCEPTION_REWARD_MAX_NEW_TOKENS)
EVAL_FORMAT_REWARD_ENABLED = env_bool("DYME_EVAL_FORMAT_REWARD", EVAL_FORMAT_REWARD_ENABLED)
EVAL_FORMAT_REWARD_WEIGHT = env_float("DYME_EVAL_FORMAT_REWARD_WEIGHT", EVAL_FORMAT_REWARD_WEIGHT)
TEACHER_CORRECT_REPAIR_MODE = env_str("DYME_TEACHER_CORRECT_REPAIR_MODE", TEACHER_CORRECT_REPAIR_MODE)
TEACHER_SFT_REPAIR_SCOPE = env_str("DYME_TEACHER_SFT_REPAIR_SCOPE", TEACHER_SFT_REPAIR_SCOPE)
TEACHER_SFT_REPAIR_SLOTS = env_int("DYME_TEACHER_SFT_REPAIR_SLOTS", TEACHER_SFT_REPAIR_SLOTS)
TEACHER_SFT_TARGET_MAX_TOKENS = env_int("DYME_TEACHER_SFT_TARGET_MAX_TOKENS", TEACHER_SFT_TARGET_MAX_TOKENS)
TEACHER_SFT_SANITIZE_PRIVILEGED = env_bool("DYME_TEACHER_SFT_SANITIZE_PRIVILEGED", TEACHER_SFT_SANITIZE_PRIVILEGED)
TEACHER_SFT_TARGET_CONSTRAINT = env_str("DYME_TEACHER_SFT_TARGET_CONSTRAINT", TEACHER_SFT_TARGET_CONSTRAINT)
TEACHER_SFT_TARGET_STYLE = env_str("DYME_TEACHER_SFT_TARGET_STYLE", TEACHER_SFT_TARGET_STYLE)
ONLINE_SFT_TARGET_STYLE = env_str("DYME_ONLINE_SFT_TARGET_STYLE", ONLINE_SFT_TARGET_STYLE)
SFT_COLD_START_STEPS = env_int("DYME_SFT_COLD_START_STEPS", SFT_COLD_START_STEPS)
PHASE_SCHEDULE_MODE = env_str("DYME_PHASE_SCHEDULE_MODE", PHASE_SCHEDULE_MODE).lower()
DYNAMIC_TRIGGER_MONITOR_ENABLED = env_bool("DYME_DYNAMIC_TRIGGER_MONITOR", DYNAMIC_TRIGGER_MONITOR_ENABLED)
DYNAMIC_TRIGGER_EMA_ALPHA = env_float("DYME_DYNAMIC_TRIGGER_EMA_ALPHA", DYNAMIC_TRIGGER_EMA_ALPHA)
DYNAMIC_TRIGGER_MIN_PROGRESS = env_float("DYME_DYNAMIC_TRIGGER_MIN_PROGRESS", DYNAMIC_TRIGGER_MIN_PROGRESS)
DYNAMIC_TRIGGER_PATIENCE = env_int("DYME_DYNAMIC_TRIGGER_PATIENCE", DYNAMIC_TRIGGER_PATIENCE)
DYNAMIC_TRIGGER_SAMPLING_MIXED_MAX = env_float("DYME_DYNAMIC_TRIGGER_SAMPLING_MIXED_MAX", DYNAMIC_TRIGGER_SAMPLING_MIXED_MAX)
DYNAMIC_TRIGGER_SAMPLING_ZERO_MIN = env_float("DYME_DYNAMIC_TRIGGER_SAMPLING_ZERO_MIN", DYNAMIC_TRIGGER_SAMPLING_ZERO_MIN)
DYNAMIC_TRIGGER_RL_MIXED_MIN = env_float("DYME_DYNAMIC_TRIGGER_RL_MIXED_MIN", DYNAMIC_TRIGGER_RL_MIXED_MIN)
DYNAMIC_TRIGGER_RL_ZERO_MAX = env_float("DYME_DYNAMIC_TRIGGER_RL_ZERO_MAX", DYNAMIC_TRIGGER_RL_ZERO_MAX)
ADAPTIVE_SUPERVISION_ENABLED = env_bool("DYME_ADAPTIVE_SUPERVISION", ADAPTIVE_SUPERVISION_ENABLED)
ADAPTIVE_READINESS_SOURCE = os.environ.get(
    "DYME_ADAPTIVE_READINESS_SOURCE", ADAPTIVE_READINESS_SOURCE
).strip().lower()
ADAPTIVE_EMA_ALPHA = env_float("DYME_ADAPTIVE_EMA_ALPHA", ADAPTIVE_EMA_ALPHA)
ADAPTIVE_TARGET_READINESS = env_float("DYME_ADAPTIVE_TARGET_READINESS", ADAPTIVE_TARGET_READINESS)
ADAPTIVE_OPSD_INITIAL_WEIGHT = env_float("DYME_ADAPTIVE_OPSD_INITIAL_WEIGHT", ADAPTIVE_OPSD_INITIAL_WEIGHT)
ADAPTIVE_OPSD_FINAL_WEIGHT = env_float("DYME_ADAPTIVE_OPSD_FINAL_WEIGHT", ADAPTIVE_OPSD_FINAL_WEIGHT)
ADAPTIVE_TEACHER_INITIAL_WEIGHT = env_float("DYME_ADAPTIVE_TEACHER_INITIAL_WEIGHT", ADAPTIVE_TEACHER_INITIAL_WEIGHT)
ADAPTIVE_TEACHER_FINAL_WEIGHT = env_float("DYME_ADAPTIVE_TEACHER_FINAL_WEIGHT", ADAPTIVE_TEACHER_FINAL_WEIGHT)
ADAPTIVE_OPSD_INITIAL_CAP = env_int("DYME_ADAPTIVE_OPSD_INITIAL_CAP", ADAPTIVE_OPSD_INITIAL_CAP)
ADAPTIVE_OPSD_FINAL_CAP = env_int("DYME_ADAPTIVE_OPSD_FINAL_CAP", ADAPTIVE_OPSD_FINAL_CAP)
GLOBAL_SIGNAL_LOGGING_ENABLED = env_bool("DYME_GLOBAL_SIGNAL_LOGGING", GLOBAL_SIGNAL_LOGGING_ENABLED)
SIGNAL_UTILITY_ROUTING_ENABLED = env_bool("DYME_SIGNAL_UTILITY_ROUTING", SIGNAL_UTILITY_ROUTING_ENABLED)
SIGNAL_UTILITY_REWARD_STD_SCALE = env_float("DYME_SIGNAL_UTILITY_REWARD_STD_SCALE", SIGNAL_UTILITY_REWARD_STD_SCALE)
SIGNAL_UTILITY_ALLOW_GRPO_ON_FORMAT_BAD = env_bool("DYME_SIGNAL_UTILITY_ALLOW_GRPO_ON_FORMAT_BAD", SIGNAL_UTILITY_ALLOW_GRPO_ON_FORMAT_BAD)
SIGNAL_UTILITY_GRPO_BASE = env_float("DYME_SIGNAL_UTILITY_GRPO_BASE", SIGNAL_UTILITY_GRPO_BASE)
SIGNAL_UTILITY_GRPO_CORRECT_BONUS = env_float("DYME_SIGNAL_UTILITY_GRPO_CORRECT_BONUS", SIGNAL_UTILITY_GRPO_CORRECT_BONUS)
SIGNAL_UTILITY_GRPO_MIXED_BONUS = env_float("DYME_SIGNAL_UTILITY_GRPO_MIXED_BONUS", SIGNAL_UTILITY_GRPO_MIXED_BONUS)
SIGNAL_UTILITY_GRPO_SIGNAL_WEIGHT = env_float("DYME_SIGNAL_UTILITY_GRPO_SIGNAL_WEIGHT", SIGNAL_UTILITY_GRPO_SIGNAL_WEIGHT)
SIGNAL_UTILITY_GRPO_READINESS_WEIGHT = env_float("DYME_SIGNAL_UTILITY_GRPO_READINESS_WEIGHT", SIGNAL_UTILITY_GRPO_READINESS_WEIGHT)
SIGNAL_UTILITY_OPD_BASE = env_float("DYME_SIGNAL_UTILITY_OPD_BASE", SIGNAL_UTILITY_OPD_BASE)
SIGNAL_UTILITY_OPD_TEACHER_BONUS = env_float("DYME_SIGNAL_UTILITY_OPD_TEACHER_BONUS", SIGNAL_UTILITY_OPD_TEACHER_BONUS)
SIGNAL_UTILITY_OPD_WRONG_BONUS = env_float("DYME_SIGNAL_UTILITY_OPD_WRONG_BONUS", SIGNAL_UTILITY_OPD_WRONG_BONUS)
SIGNAL_UTILITY_OPD_GAP_WEIGHT = env_float("DYME_SIGNAL_UTILITY_OPD_GAP_WEIGHT", SIGNAL_UTILITY_OPD_GAP_WEIGHT)
SIGNAL_UTILITY_OPD_ALL_WRONG_BONUS = env_float("DYME_SIGNAL_UTILITY_OPD_ALL_WRONG_BONUS", SIGNAL_UTILITY_OPD_ALL_WRONG_BONUS)
SIGNAL_UTILITY_OPD_TEACHER_NEED_WEIGHT = env_float("DYME_SIGNAL_UTILITY_OPD_TEACHER_NEED_WEIGHT", SIGNAL_UTILITY_OPD_TEACHER_NEED_WEIGHT)
SIGNAL_UTILITY_OPD_FORMAT_PENALTY = env_float("DYME_SIGNAL_UTILITY_OPD_FORMAT_PENALTY", SIGNAL_UTILITY_OPD_FORMAT_PENALTY)
SIGNAL_UTILITY_SFT_BASE = env_float("DYME_SIGNAL_UTILITY_SFT_BASE", SIGNAL_UTILITY_SFT_BASE)
SIGNAL_UTILITY_SFT_FORMAT_BAD_BONUS = env_float("DYME_SIGNAL_UTILITY_SFT_FORMAT_BAD_BONUS", SIGNAL_UTILITY_SFT_FORMAT_BAD_BONUS)
SIGNAL_UTILITY_SFT_CLIPPED_BONUS = env_float("DYME_SIGNAL_UTILITY_SFT_CLIPPED_BONUS", SIGNAL_UTILITY_SFT_CLIPPED_BONUS)
SIGNAL_UTILITY_SFT_ALL_WRONG_BONUS = env_float("DYME_SIGNAL_UTILITY_SFT_ALL_WRONG_BONUS", SIGNAL_UTILITY_SFT_ALL_WRONG_BONUS)
SIGNAL_UTILITY_SFT_LOW_SIGNAL_BONUS = env_float("DYME_SIGNAL_UTILITY_SFT_LOW_SIGNAL_BONUS", SIGNAL_UTILITY_SFT_LOW_SIGNAL_BONUS)
SIGNAL_UTILITY_SFT_CORRECT_PENALTY = env_float("DYME_SIGNAL_UTILITY_SFT_CORRECT_PENALTY", SIGNAL_UTILITY_SFT_CORRECT_PENALTY)
SIGNAL_UTILITY_SKIP_CLIPPED_WITHOUT_TEACHER = env_bool("DYME_SIGNAL_UTILITY_SKIP_CLIPPED_WITHOUT_TEACHER", SIGNAL_UTILITY_SKIP_CLIPPED_WITHOUT_TEACHER)
SIGNAL_UTILITY_MODE_STABLE_ENABLED = env_bool("DYME_SIGNAL_UTILITY_MODE_STABLE", SIGNAL_UTILITY_MODE_STABLE_ENABLED)
SIGNAL_UTILITY_EMA_BETA = env_float("DYME_SIGNAL_UTILITY_EMA_BETA", SIGNAL_UTILITY_EMA_BETA)
SIGNAL_UTILITY_SWITCH_MARGIN = env_float("DYME_SIGNAL_UTILITY_SWITCH_MARGIN", SIGNAL_UTILITY_SWITCH_MARGIN)
SIGNAL_UTILITY_MIN_HOLD_STEPS = env_int("DYME_SIGNAL_UTILITY_MIN_HOLD_STEPS", SIGNAL_UTILITY_MIN_HOLD_STEPS)
CHART_COT_VERIFY_ENABLED = env_bool("DYME_CHART_COT_VERIFY", CHART_COT_VERIFY_ENABLED)
CHART_COT_GATE_MODE = env_str("DYME_CHART_COT_GATE_MODE", CHART_COT_GATE_MODE).lower()
CHART_COT_REQUIRE_Q3 = env_bool("DYME_CHART_COT_REQUIRE_Q3", CHART_COT_REQUIRE_Q3)
CHART_COT_LOG_SAMPLES = env_bool("DYME_CHART_COT_LOG_SAMPLES", CHART_COT_LOG_SAMPLES)
CHART_COT_MAX_LOG_SAMPLES = env_int("DYME_CHART_COT_MAX_LOG_SAMPLES", CHART_COT_MAX_LOG_SAMPLES)

MODEL_CONFIG = dict(base.MODEL_CONFIG)

_dyme_args = {
    **base.CONFIG["training"]["dyme_args"],
    "output_dir": OUTPUT_DIR,
    "num_train_epochs": NUM_TRAIN_EPOCHS,
}
_dyme_args["save_strategy"] = env_str("DYME_SAVE_STRATEGY", _dyme_args.get("save_strategy", "epoch"))
# Do not inherit max_steps from a prior smoke shell export; full run uses epochs.
_dyme_args.pop("max_steps", None)
_max_steps = env_optional_int("DYME_MAX_STEPS")
if _max_steps is not None:
    _dyme_args["max_steps"] = _max_steps
_save_total_limit = env_optional_int("DYME_SAVE_TOTAL_LIMIT")
if _save_total_limit is not None:
    _dyme_args["save_total_limit"] = _save_total_limit
_max_completion_length = env_optional_int("DYME_MAX_COMPLETION_LENGTH")
if _max_completion_length is not None:
    _dyme_args["max_completion_length"] = _max_completion_length
_temperature = env_optional_float("DYME_TEMPERATURE")
if _temperature is not None:
    _dyme_args["temperature"] = _temperature
_top_p = env_optional_float("DYME_TOP_P")
if _top_p is not None:
    _dyme_args["top_p"] = _top_p
_repetition_penalty = env_optional_float("DYME_REPETITION_PENALTY")
if _repetition_penalty is not None:
    _dyme_args["repetition_penalty"] = _repetition_penalty
_num_generations = env_optional_int("DYME_NUM_GENERATIONS")
if _num_generations is not None:
    _dyme_args["num_generations"] = _num_generations
_per_device_train_batch_size = env_optional_int("DYME_PER_DEVICE_TRAIN_BATCH_SIZE")
if _per_device_train_batch_size is not None:
    _dyme_args["per_device_train_batch_size"] = _per_device_train_batch_size
_gradient_accumulation_steps = env_optional_int("DYME_GRADIENT_ACCUMULATION_STEPS")
if _gradient_accumulation_steps is not None:
    _dyme_args["gradient_accumulation_steps"] = _gradient_accumulation_steps
if os.environ.get("DYME_GRADIENT_CHECKPOINTING", "").strip():
    _dyme_args["gradient_checkpointing"] = env_bool(
        "DYME_GRADIENT_CHECKPOINTING",
        bool(_dyme_args.get("gradient_checkpointing", False)),
    )


def _default_format_hint(prompt_profile: str) -> str:
    if prompt_profile == "chartqa_oracle_hint":
        return CHARTQA_ORACLE_HINT
    return CHARTQA_SHORT_ANSWER_HINT

DYME_OPSD_CONFIG = {
    **base.DYME_OPSD_CONFIG,
    "enabled": True,
    "phase_schedule": {
        "mode": PHASE_SCHEDULE_MODE,
    },
    "mode": OPSD_MODE,
    "text_include_gold": False,
    "format_only_hint": env_str("DYME_TEACHER_FORMAT_HINT", _default_format_hint(TEACHER_PROBE_PROMPT_PROFILE)),
    "privileged_profile": PRIVILEGE_PROFILE,
    "privileged_providers": PROBE_PROVIDERS,
    "gate": {
        **base.DYME_OPSD_CONFIG.get("gate", {}),
        "per_completion_opsd": True,
        "online_sft_on_all_wrong": True,
        "require_format_for_opsd": False,
        # Default remains no cold-start; selected variants can enable a short SFT anchor.
        "sft_cold_start_steps": SFT_COLD_START_STEPS,
        "sft_cold_start_frac": 0.0,
        "signal_aware_routing": SIGNAL_AWARE_ROUTING,
        "signal_reward_std_min": SIGNAL_REWARD_STD_MIN,
        "degenerate_hard_override": DEGENERATE_HARD_OVERRIDE,
        "clipped_hard_override": CLIPPED_HARD_OVERRIDE,
        "online_sft_target_style": ONLINE_SFT_TARGET_STYLE,
    },
    "loss": {
        **base.DYME_OPSD_CONFIG.get("loss", {}),
        "loss_type": LOSS_TYPE,
        "srkl_alpha": SRKL_ALPHA,
        "opsd_weight": OPSD_WEIGHT,
        "grpo_weight": GRPO_WEIGHT,
        "teacher_traj_fkl_weight": TEACHER_TRAJ_FKL_WEIGHT,
        "variance_adaptive": OPSD_VARIANCE_ADAPTIVE,
        "adaptive_std_target": OPSD_ADAPTIVE_STD_TARGET,
        "adaptive_max_mult": OPSD_ADAPTIVE_MAX_MULT,
        "weight_decay": {
            "enabled": OPSD_WEIGHT_DECAY,
            "start_step": OPSD_DECAY_START_STEP,
            "end_step": OPSD_DECAY_END_STEP,
            "start_progress": OPSD_DECAY_START_PROGRESS,
            "end_progress": OPSD_DECAY_END_PROGRESS,
            "final_weight": OPSD_FINAL_WEIGHT,
        },
        "route_cap": {
            "enabled": OPSD_MAX_PER_PROMPT > 0,
            "max_per_prompt": OPSD_MAX_PER_PROMPT,
            "after_step": OPSD_MAX_PER_PROMPT_AFTER_STEP,
            "schedule_mode": PHASE_SCHEDULE_MODE,
            "start_progress": OPSD_ROUTE_CAP_START_PROGRESS,
            "overflow_route": OPSD_OVERFLOW_ROUTE,
        },
    },
    "teacher_probe": {
        "enabled": TEACHER_PROBE_ENABLED,
        "context_providers": PROBE_PROVIDERS,
        "batch_size": env_int("DYME_TEACHER_PROBE_BATCH_SIZE", 1),
        "max_per_batch": env_int("DYME_TEACHER_PROBE_MAX_PER_BATCH", 0),
        "max_new_tokens": env_int("DYME_TEACHER_PROBE_MAX_NEW_TOKENS", 96),
        "do_sample": env_bool("DYME_TEACHER_PROBE_DO_SAMPLE", False),
        "temperature": env_float("DYME_TEACHER_PROBE_TEMPERATURE", 0.0),
        "top_p": env_float("DYME_TEACHER_PROBE_TOP_P", 1.0),
        "repetition_penalty": env_float("DYME_TEACHER_PROBE_REPETITION_PENALTY", 1.2),
        "max_relative_change": env_float("DYME_TEACHER_PROBE_RELAXED_TOL", 0.05),
        "prompt_profile": TEACHER_PROBE_PROMPT_PROFILE,
        "answer_parser": env_str("DYME_TEACHER_PROBE_ANSWER_PARSER", "chartqa_final_answer"),
        "skip_no_evidence": env_bool("DYME_TEACHER_PROBE_SKIP_NO_EVIDENCE", True),
        "probe_all_wrong_after_step": env_optional_int("DYME_TEACHER_PROBE_ALL_WRONG_AFTER_STEP"),
        "candidate_log": {
            "enabled": env_bool("DYME_TEACHER_PROBE_CANDIDATE_LOG", True),
        },
    },
    "teacher_trajectory": {
        "enabled": TEACHER_TRAJECTORY_ENABLED,
        "loss_type": env_str("DYME_TEACHER_TRAJ_LOSS_TYPE", "fkl"),
        "weight": TEACHER_TRAJ_FKL_WEIGHT,
        "max_new_tokens": env_int("DYME_TEACHER_TRAJ_MAX_NEW_TOKENS", 128),
        "weight_decay": {
            "enabled": TEACHER_TRAJ_WEIGHT_DECAY,
            "start_step": TEACHER_TRAJ_DECAY_START_STEP,
            "end_step": TEACHER_TRAJ_DECAY_END_STEP,
            "start_progress": TEACHER_TRAJ_DECAY_START_PROGRESS,
            "end_progress": TEACHER_TRAJ_DECAY_END_PROGRESS,
            "final_weight": TEACHER_TRAJ_FINAL_WEIGHT,
        },
    },
    "teacher_correct_repair": {
        "mode": TEACHER_CORRECT_REPAIR_MODE,
        "scope": TEACHER_SFT_REPAIR_SCOPE,
        "slots_per_prompt": TEACHER_SFT_REPAIR_SLOTS,
        "target_max_tokens": TEACHER_SFT_TARGET_MAX_TOKENS,
        "sanitize_privileged": TEACHER_SFT_SANITIZE_PRIVILEGED,
        "target_constraint": TEACHER_SFT_TARGET_CONSTRAINT,
        "target_style": TEACHER_SFT_TARGET_STYLE,
    },
    "chart_cot_quality_gate": {
        "enabled": CHART_COT_VERIFY_ENABLED,
        "mode": CHART_COT_GATE_MODE,
        "require_quality": "Q3" if CHART_COT_REQUIRE_Q3 else "Q2",
        "log_samples": CHART_COT_LOG_SAMPLES,
        "max_log_samples": CHART_COT_MAX_LOG_SAMPLES,
    },
    "effective_sampling": {
        "enabled": EFFECTIVE_SAMPLING_ENABLED,
        "after_step": EFFECTIVE_SAMPLING_AFTER_STEP,
        "schedule_mode": PHASE_SCHEDULE_MODE,
        "start_progress": EFFECTIVE_SAMPLING_START_PROGRESS,
        "mixed_weight": EFFECTIVE_SAMPLING_MIXED_WEIGHT,
        "all_wrong_weight": EFFECTIVE_SAMPLING_ALL_WRONG_WEIGHT,
        "all_correct_weight": EFFECTIVE_SAMPLING_ALL_CORRECT_WEIGHT,
        "unknown_weight": EFFECTIVE_SAMPLING_UNKNOWN_WEIGHT,
        "reward_std_bonus": EFFECTIVE_SAMPLING_REWARD_STD_BONUS,
    },
    "dynamic_trigger_monitor": {
        "enabled": DYNAMIC_TRIGGER_MONITOR_ENABLED,
        "ema_alpha": DYNAMIC_TRIGGER_EMA_ALPHA,
        "min_progress": DYNAMIC_TRIGGER_MIN_PROGRESS,
        "patience_steps": DYNAMIC_TRIGGER_PATIENCE,
        "sampling_mixed_max": DYNAMIC_TRIGGER_SAMPLING_MIXED_MAX,
        "sampling_zero_loss_min": DYNAMIC_TRIGGER_SAMPLING_ZERO_MIN,
        "rl_mixed_min": DYNAMIC_TRIGGER_RL_MIXED_MIN,
        "rl_zero_loss_max": DYNAMIC_TRIGGER_RL_ZERO_MAX,
    },
    "adaptive_supervision": {
        "enabled": ADAPTIVE_SUPERVISION_ENABLED,
        "readiness_source": ADAPTIVE_READINESS_SOURCE,
        "ema_alpha": ADAPTIVE_EMA_ALPHA,
        "target_readiness": ADAPTIVE_TARGET_READINESS,
        "opsd_initial_weight": ADAPTIVE_OPSD_INITIAL_WEIGHT,
        "opsd_final_weight": ADAPTIVE_OPSD_FINAL_WEIGHT,
        "teacher_initial_weight": ADAPTIVE_TEACHER_INITIAL_WEIGHT,
        "teacher_final_weight": ADAPTIVE_TEACHER_FINAL_WEIGHT,
        "opd_initial_cap": ADAPTIVE_OPSD_INITIAL_CAP,
        "opd_final_cap": ADAPTIVE_OPSD_FINAL_CAP,
    },
    "signal_utility_routing": {
        "enabled": SIGNAL_UTILITY_ROUTING_ENABLED,
        "reward_std_scale": SIGNAL_UTILITY_REWARD_STD_SCALE,
        "allow_grpo_on_format_bad": SIGNAL_UTILITY_ALLOW_GRPO_ON_FORMAT_BAD,
        "grpo_base": SIGNAL_UTILITY_GRPO_BASE,
        "grpo_correct_bonus": SIGNAL_UTILITY_GRPO_CORRECT_BONUS,
        "grpo_mixed_bonus": SIGNAL_UTILITY_GRPO_MIXED_BONUS,
        "grpo_signal_weight": SIGNAL_UTILITY_GRPO_SIGNAL_WEIGHT,
        "grpo_readiness_weight": SIGNAL_UTILITY_GRPO_READINESS_WEIGHT,
        "opd_base": SIGNAL_UTILITY_OPD_BASE,
        "opd_teacher_bonus": SIGNAL_UTILITY_OPD_TEACHER_BONUS,
        "opd_wrong_bonus": SIGNAL_UTILITY_OPD_WRONG_BONUS,
        "opd_gap_weight": SIGNAL_UTILITY_OPD_GAP_WEIGHT,
        "opd_all_wrong_bonus": SIGNAL_UTILITY_OPD_ALL_WRONG_BONUS,
        "opd_teacher_need_weight": SIGNAL_UTILITY_OPD_TEACHER_NEED_WEIGHT,
        "opd_format_penalty": SIGNAL_UTILITY_OPD_FORMAT_PENALTY,
        "sft_base": SIGNAL_UTILITY_SFT_BASE,
        "sft_format_bad_bonus": SIGNAL_UTILITY_SFT_FORMAT_BAD_BONUS,
        "sft_clipped_bonus": SIGNAL_UTILITY_SFT_CLIPPED_BONUS,
        "sft_all_wrong_bonus": SIGNAL_UTILITY_SFT_ALL_WRONG_BONUS,
        "sft_low_signal_bonus": SIGNAL_UTILITY_SFT_LOW_SIGNAL_BONUS,
        "sft_correct_penalty": SIGNAL_UTILITY_SFT_CORRECT_PENALTY,
        "skip_clipped_without_teacher": SIGNAL_UTILITY_SKIP_CLIPPED_WITHOUT_TEACHER,
        "mode_stable_enabled": SIGNAL_UTILITY_MODE_STABLE_ENABLED,
        "mode_stable_ema_beta": SIGNAL_UTILITY_EMA_BETA,
        "mode_stable_switch_margin": SIGNAL_UTILITY_SWITCH_MARGIN,
        "mode_stable_min_hold_steps": SIGNAL_UTILITY_MIN_HOLD_STEPS,
    },
    "global_signal_logging": {
        "enabled": GLOBAL_SIGNAL_LOGGING_ENABLED,
    },
    "positive_replay": {
        "enabled": POSITIVE_REPLAY_ENABLED,
        "dataset_path": POSITIVE_REPLAY_DATASET,
        "weight": POSITIVE_REPLAY_WEIGHT,
        "batch_size": POSITIVE_REPLAY_BATCH_SIZE,
        "after_step": POSITIVE_REPLAY_AFTER_STEP,
        "until_step": POSITIVE_REPLAY_UNTIL_STEP,
        "max_rows": POSITIVE_REPLAY_MAX_ROWS,
        "seed": POSITIVE_REPLAY_SEED,
    },
    "rollout_replay": {
        "enabled": ROLLOUT_REPLAY_ENABLED,
        "weight": ROLLOUT_REPLAY_WEIGHT,
        "capacity": ROLLOUT_REPLAY_CAPACITY,
        "batch_size": ROLLOUT_REPLAY_BATCH_SIZE,
        "after_step": ROLLOUT_REPLAY_AFTER_STEP,
        "until_step": ROLLOUT_REPLAY_UNTIL_STEP,
        "max_age_steps": ROLLOUT_REPLAY_MAX_AGE_STEPS,
        "min_abs_advantage": ROLLOUT_REPLAY_MIN_ABS_ADVANTAGE,
        "correct_threshold": ROLLOUT_REPLAY_CORRECT_THRESHOLD,
        "priority_alpha": ROLLOUT_REPLAY_PRIORITY_ALPHA,
        "positive_only": ROLLOUT_REPLAY_POSITIVE_ONLY,
        "seed": ROLLOUT_REPLAY_SEED,
    },
    "effective_group_filter": {
        "enabled": EFFECTIVE_GROUP_FILTER_ENABLED,
        "after_step": EFFECTIVE_GROUP_FILTER_AFTER_STEP,
        "all_wrong_keep_per_prompt": EFFECTIVE_GROUP_FILTER_ALL_WRONG_KEEP,
        "filter_all_correct": EFFECTIVE_GROUP_FILTER_ALL_CORRECT,
    },
    "perception_reward": {
        "enabled": PERCEPTION_REWARD_ENABLED,
        "source": PERCEPTION_REWARD_SOURCE,
        "weight": PERCEPTION_REWARD_WEIGHT,
        "batch_size": PERCEPTION_REWARD_BATCH_SIZE,
        "max_new_tokens": PERCEPTION_REWARD_MAX_NEW_TOKENS,
    },
    "eval_format_reward": {
        "enabled": EVAL_FORMAT_REWARD_ENABLED,
        "weight": EVAL_FORMAT_REWARD_WEIGHT,
    },
    "visual_supervision": build_visual_supervision_config(),
    "debug": {
        **base.DYME_OPSD_CONFIG.get("debug", {}),
        "detail_every": env_int("DYME_OPSD_DETAIL_EVERY", 0),
    },
}

LAUNCH_CONFIG = {
    "gradient_checkpointing_enable": env_bool(
        "DYME_GRADIENT_CHECKPOINTING",
        bool(_dyme_args.get("gradient_checkpointing", False)),
    ),
    "opsd_detail_every": DYME_OPSD_CONFIG["debug"]["detail_every"],
    "opsd_detail_min_free_gb": env_float("DYME_OPSD_DETAIL_MIN_FREE_GB", 4.0),
    "teacher_device_map": env_str("DYME_TEACHER_DEVICE_MAP", "auto"),
    "pytorch_cuda_alloc_conf": env_str("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True"),
}

_teacher_map = LAUNCH_CONFIG["teacher_device_map"]
if _teacher_map and _teacher_map.lower() not in ("none", "null"):
    MODEL_CONFIG["teacher_device_map"] = _teacher_map

DEPLOT_CONFIG = {
    **_BASE_DEPLOT_CONFIG,
    "enabled": env_bool("DYME_DEPLOT_ENABLED", False),
}

CONFIG = {
    "model": MODEL_CONFIG,
    "training": {
        **base.CONFIG["training"],
        "dyme_args": _dyme_args,
    },
    "rl": base.CONFIG["rl"],
    "opsd": DYME_OPSD_CONFIG,
    "client": base.CONFIG["client"],
    "dataset": base.CONFIG["dataset"],
    "checkpoint_eval": dict(base.CONFIG.get("checkpoint_eval", {})),
    "launch": LAUNCH_CONFIG,
    "deplot": DEPLOT_CONFIG,
}
